str1 = input().lower()
str2 = input().lower()
setA = set(str1.split())
setB = set(str2.split())
a = list(setA | setB)
b = list(setA & setB)
a.sort() ; b.sort()
for i in a: print(i, end =' ')
print()
for i in b: print(i, end = ' ')